### ISSUE TITLE
Correlation error column selected twice

### ISSUE THREAD

**Issue by d-callan** [microbiomeDB/microbiomeComputations#3]
From microbiomeComputations created by [asizemore](https://github.com/asizemore): VEuPathDB/microbiomeComputations#79  

<img width="1754" alt="Screen Shot 2024-01-24 at 11 37 53 AM" src="https://github.com/VEuPathDB/microbiomeComputations/assets/11710234/856a10c5-52d2-4159-ab58-25e65908f975">

Study diabimmune

Found on qa today 11:38am

**Comment by asizemore** [comment]
<img width="1277" alt="Screen Shot 2024-03-05 at 12 37 29 PM" src="https://github.com/microbiomeDB/microbiomeComputations/assets/11710234/ad595a66-cbbc-42d0-a25b-47285ea5e382">

Seen on live today. Issue has resolved itself. Closing
